version: '3.8'

services:
  db:
    image: postgres:15
    container_name: airbnb_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: airbnb
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  data: